### ISSUE TITLE
GH Package Registry requires the repository name to be lowercase when pushing it

### ISSUE THREAD

**Issue by r0adkll** [matootie/github-docker#1]
When you are executing this line: https://github.com/matootie/github-docker/blob/67591dc3635748d4a3f8984d031fcc0149b7982f/index.js#L58 you need to force lower case on the repository name, otherwise, the action will fail.

**Comment by matootie** [comment]
Nice, this is true for the image name as well. I'm fixing this right away.

**Comment by matootie** [comment]
Patched into `v1.0.1`

Thanks for the help!

**Comment by r0adkll** [comment]
Awesome! Thanks for the quick patch!
